version: '3.6'

services:
  aspnetcoreangular:
    image: ${DOCKER_REGISTRY-}aspnetcoreangular
    build:
      context: .
      dockerfile: src/Presentation/Web/Dockerfile
    networks:
      - app-network

  aspnetcorests:
    image: ${DOCKER_REGISTRY-}aspnetcorests
    build:
      context: .
      dockerfile: src/Presentation/STS/Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
