name: Publish to GitHub Pages
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 
    - name: Install Antora
      run: cd docs-site && npm i antora@3.1
    - name: List directory contents
      run: ls
    - name: Generate Site
      run: cd docs-site && npx antora --fetch antora-playbook.yml
    - name: List directory contents after generation
      run: ls
    - name: List directory contents inside docs-site
      run: ls ./docs-site    
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs-site/build/site
