name: VM-STS

on:
  push:
    branches:
      - master

jobs:
  build-test-publish-ftp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.100
      - name: Build
        run: dotnet build AspNetCoreAngular.sln --configuration Release
      - name: Test
        run: dotnet test AspNetCoreAngular.sln